'use client';
import Link from 'next/link';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ArrowLeft, Download, ImagePlus, Type, Stamp, Highlighter, Undo2, Redo2, Building2, RotateCw, Trash2, Copy, Save, PenLine } from 'lucide-react';
import type { EditorPage, Overlay, OverlayType } from '@/lib/editor-types';
import { exportEditedPdf } from '@/lib/export-pdf';
import type { BrandData } from '@/lib/pdf';

const defaultBrand:BrandData={companyName:'',address:'',email:'',phone:'',vatNumber:'',website:'',footerText:''};
type Snapshot={pages:EditorPage[];overlays:Overlay[]};

export default function Editor(){
  const [docId,setDocId]=useState(''); const [name,setName]=useState('Documento.pdf'); const [source,setSource]=useState<ArrayBuffer|null>(null);
  const [pages,setPages]=useState<EditorPage[]>([]); const [selectedPage,setSelectedPage]=useState(''); const [overlays,setOverlays]=useState<Overlay[]>([]); const [selected,setSelected]=useState('');
  const [brand,setBrand]=useState<BrandData>(defaultBrand); const [status,setStatus]=useState('Caricamento documento…'); const [history,setHistory]=useState<Snapshot[]>([]); const [future,setFuture]=useState<Snapshot[]>([]); const [showSign,setShowSign]=useState(false);
  const snapshot=useCallback(()=>{setHistory(h=>[...h.slice(-24),{pages:structuredClone(pages),overlays:structuredClone(overlays)}]);setFuture([])},[pages,overlays]);
  useEffect(()=>{const saved=localStorage.getItem('pdfbrand-brand');if(saved)try{setBrand(JSON.parse(saved))}catch{}; const id=new URLSearchParams(location.search).get('id')||localStorage.getItem('pdfbrand-doc-id')||''; if(!id){setStatus('Nessun documento selezionato.');return} setDocId(id); (async()=>{try{const meta=await fetch(`/api/documents/${id}`).then(r=>r.json());if(meta.error)throw new Error(meta.error);setName(meta.name);const buf=await fetch(`/api/documents/${id}/file`).then(r=>r.arrayBuffer());setSource(buf);const initial=Array.from({length:meta.pageCount},(_,i)=>({id:crypto.randomUUID(),sourceIndex:i,rotation:0}));const savedState=await fetch(`/api/documents/${id}/state`).then(r=>r.json()).catch(()=>({state:null}));if(savedState?.pages?.length){setPages(savedState.pages);setOverlays(savedState.overlays||[]);if(savedState.brand)setBrand(savedState.brand);setSelectedPage(savedState.pages[0].id)}else{setPages(initial);setSelectedPage(initial[0]?.id||'')}setStatus('Documento pronto.')}catch(e){setStatus((e as Error).message)}})()},[]);
  const active=overlays.find(o=>o.id===selected);
  const addOverlay=(type:OverlayType,data:Partial<Overlay>={})=>{if(!selectedPage)return;snapshot();const o:Overlay={id:crypto.randomUUID(),type,pageId:selectedPage,x:.18,y:.18,w:type==='text'?.28:.24,h:type==='text'?.06:.12,fontSize:18,color:'#111827',opacity:type==='highlight'?.35:1,...data};setOverlays(v=>[...v,o]);setSelected(o.id)};
  const addImage=async(file?:File,type:OverlayType='image')=>{if(!file)return;addOverlay(type,{dataUrl:await fileToDataURL(file),w:.28,h:.16})};
  const deletePage=()=>{if(pages.length<=1)return; snapshot(); const idx=pages.findIndex(p=>p.id===selectedPage);setPages(p=>p.filter(x=>x.id!==selectedPage));setOverlays(o=>o.filter(x=>x.pageId!==selectedPage));setSelectedPage(pages[Math.max(0,idx-1)]?.id||pages[0].id)};
  const duplicatePage=()=>{const p=pages.find(x=>x.id===selectedPage);if(!p)return;snapshot();const copy={...p,id:crypto.randomUUID()};const idx=pages.findIndex(x=>x.id===selectedPage);setPages(v=>[...v.slice(0,idx+1),copy,...v.slice(idx+1)]);setOverlays(v=>[...v,...v.filter(o=>o.pageId===p.id).map(o=>({...o,id:crypto.randomUUID(),pageId:copy.id}))]);setSelectedPage(copy.id)};
  const rotatePage=()=>{snapshot();setPages(v=>v.map(p=>p.id===selectedPage?{...p,rotation:(p.rotation+90)%360}:p))};
  const movePage=(from:number,to:number)=>{if(from===to||to<0||to>=pages.length)return;snapshot();const next=[...pages];const [p]=next.splice(from,1);next.splice(to,0,p);setPages(next)};
  const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[{pages:structuredClone(pages),overlays:structuredClone(overlays)},...f]);setPages(prev.pages);setOverlays(prev.overlays);setHistory(h=>h.slice(0,-1))};
  const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,{pages:structuredClone(pages),overlays:structuredClone(overlays)}]);setPages(next.pages);setOverlays(next.overlays);setFuture(f=>f.slice(1))};
  const renderOutput=async()=>{if(!source)return null;return exportEditedPdf(source,pages,overlays,brand)};
  const save=async()=>{try{setStatus('Salvataggio progetto…');const r=await fetch(`/api/documents/${docId}/state`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({pages,overlays,brand})});if(!r.ok)throw new Error((await r.json()).error);setStatus('Progetto salvato sul server.')}catch(e){setStatus((e as Error).message)}};
  const download=async()=>{const out=await renderOutput();if(!out)return;const url=URL.createObjectURL(new Blob([out],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=name.replace(/\.pdf$/i,'')+'-modificato.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const saveBrand=()=>{localStorage.setItem('pdfbrand-brand',JSON.stringify(brand));setStatus('Brand Kit salvato nel browser.')};
  return <div className="shell"><header className="topbar"><div className="top-left"><Link href="/" className="tool icon-only"><ArrowLeft size={18}/></Link><div className="brand">PDF Brand <span>Studio</span></div><strong className="docname">{name}</strong></div><div className="top-actions"><button className="btn btn-soft" onClick={save}><Save size={16}/> Salva</button><button className="btn btn-primary" onClick={download}><Download size={16}/> Scarica PDF</button></div></header>
  <div className="toolbar"><button className="tool" onClick={()=>addOverlay('text',{text:'Nuovo testo'})}><Type size={16}/> Testo</button><label className="tool"><ImagePlus size={16}/> Immagine<input hidden type="file" accept="image/png,image/jpeg" onChange={e=>addImage(e.target.files?.[0])}/></label><button className="tool" onClick={()=>setShowSign(true)}><Stamp size={16}/> Firma</button><button className="tool" onClick={()=>addOverlay('highlight')}><Highlighter size={16}/> Evidenzia</button><button className="tool icon-only" onClick={undo} disabled={!history.length}><Undo2 size={16}/></button><button className="tool icon-only" onClick={redo} disabled={!future.length}><Redo2 size={16}/></button><span className="toolbar-sep"/><button className="tool" onClick={rotatePage}><RotateCw size={16}/> Ruota</button><button className="tool" onClick={duplicatePage}><Copy size={16}/> Duplica</button><button className="tool danger" onClick={deletePage} disabled={pages.length<=1}><Trash2 size={16}/> Elimina</button><button className="btn btn-primary" style={{marginLeft:'auto'}} onClick={()=>{saveBrand();setStatus('Brand Kit pronto: verrà applicato all’esportazione.')}}><Building2 size={16}/> Applica carta intestata</button></div>
  <main className="editor"><aside className="pages"><div className="eyebrow">Pagine · {pages.length}</div>{pages.map((p,i)=><div key={p.id} className={`thumb-wrap ${selectedPage===p.id?'selected':''}`} onClick={()=>setSelectedPage(p.id)}><img className="thumb-canvas" src={`/api/documents/${docId}/preview/${p.sourceIndex+1}?dpi=70&rotation=${p.rotation}`} alt={`Pagina ${i+1}`}/><div className="thumb-meta"><span>Pagina {i+1}</span><span><button onClick={e=>{e.stopPropagation();movePage(i,i-1)}} disabled={i===0}>↑</button><button onClick={e=>{e.stopPropagation();movePage(i,i+1)}} disabled={i===pages.length-1}>↓</button></span></div></div>)}</aside>
  <section className="workspace">{pages.map((p,i)=><div key={p.id} className={`canvas-wrap ${selectedPage===p.id?'active-page':''}`} onMouseDown={()=>{setSelectedPage(p.id);setSelected('')}}><div className="page-label">Pagina {i+1}</div><div className="canvas-page"><img src={`/api/documents/${docId}/preview/${p.sourceIndex+1}?dpi=120&rotation=${p.rotation}`} alt={`Pagina ${i+1}`}/>{overlays.filter(o=>o.pageId===p.id).map(o=><OverlayBox key={o.id} overlay={o} selected={selected===o.id} onSelect={()=>setSelected(o.id)} onStart={snapshot} onChange={(patch)=>setOverlays(v=>v.map(x=>x.id===o.id?{...x,...patch}:x))}/> )}</div></div>)}</section>
  <aside className="props">{active?<OverlayProperties overlay={active} setOverlay={patch=>setOverlays(v=>v.map(o=>o.id===active.id?{...o,...patch}:o))} remove={()=>{snapshot();setOverlays(v=>v.filter(o=>o.id!==active.id));setSelected('')}}/>:<BrandProperties brand={brand} setBrand={setBrand} onLogo={async f=>setBrand({...brand,logoDataUrl:await fileToDataURL(f)})}/>}<div className="status">{status}</div></aside></main>{showSign&&<SignatureModal onClose={()=>setShowSign(false)} onDone={data=>{setShowSign(false);addOverlay('signature',{dataUrl:data,w:.28,h:.12})}}/>}</div>
}

function OverlayBox({overlay,selected,onSelect,onStart,onChange}:{overlay:Overlay;selected:boolean;onSelect:()=>void;onStart:()=>void;onChange:(p:Partial<Overlay>)=>void}){
  const drag=useRef<{mode:'move'|'resize';sx:number;sy:number;x:number;y:number;w:number;h:number;pw:number;ph:number}|null>(null);
  useEffect(()=>{const move=(e:PointerEvent)=>{const d=drag.current;if(!d)return;const dx=(e.clientX-d.sx)/d.pw,dy=(e.clientY-d.sy)/d.ph;if(d.mode==='move')onChange({x:Math.max(0,Math.min(1-d.w,d.x+dx)),y:Math.max(0,Math.min(1-d.h,d.y+dy))});else onChange({w:Math.max(.03,Math.min(1-d.x,d.w+dx)),h:Math.max(.025,Math.min(1-d.y,d.h+dy))})};const up=()=>{drag.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[onChange]);
  const begin=(e:React.PointerEvent,mode:'move'|'resize')=>{e.stopPropagation();onSelect();onStart();const page=(e.currentTarget as HTMLElement).closest('.canvas-page') as HTMLElement;drag.current={mode,sx:e.clientX,sy:e.clientY,x:overlay.x,y:overlay.y,w:overlay.w,h:overlay.h,pw:page.clientWidth,ph:page.clientHeight}};
  return <div className={`overlay ${selected?'selected':''}`} onPointerDown={e=>begin(e,'move')} style={{left:`${overlay.x*100}%`,top:`${overlay.y*100}%`,width:`${overlay.w*100}%`,height:`${overlay.h*100}%`}}>{overlay.type==='text'?<div style={{fontSize:overlay.fontSize,color:overlay.color,whiteSpace:'nowrap'}}>{overlay.text}</div>:overlay.type==='highlight'?<div className="highlight" style={{opacity:overlay.opacity}}/>:<img src={overlay.dataUrl} alt="elemento"/>}{selected&&<span className="resize-handle" onPointerDown={e=>begin(e,'resize')}/>}</div>
}
function OverlayProperties({overlay,setOverlay,remove}:{overlay:Overlay;setOverlay:(p:Partial<Overlay>)=>void;remove:()=>void}){return <><div className="eyebrow">Elemento selezionato</div><h2>{overlay.type==='text'?'Testo':overlay.type==='signature'?'Firma':overlay.type==='highlight'?'Evidenziatore':'Immagine'}</h2>{overlay.type==='text'&&<><Field label="Testo" value={overlay.text||''} onChange={v=>setOverlay({text:v})}/><div className="field"><label>Dimensione</label><input type="number" min="8" max="96" value={overlay.fontSize||18} onChange={e=>setOverlay({fontSize:Number(e.target.value)})}/></div><div className="field"><label>Colore</label><input type="color" value={overlay.color||'#111827'} onChange={e=>setOverlay({color:e.target.value})}/></div></>}{overlay.type==='highlight'&&<div className="field"><label>Opacità</label><input type="range" min="0.1" max="0.8" step="0.05" value={overlay.opacity||.35} onChange={e=>setOverlay({opacity:Number(e.target.value)})}/></div>}<button className="btn danger-btn" onClick={remove}><Trash2 size={15}/> Elimina elemento</button></>}
function BrandProperties({brand,setBrand,onLogo}:{brand:BrandData;setBrand:(b:BrandData)=>void;onLogo:(f:File)=>void}){return <><div className="eyebrow">Brand Kit</div><h2>Carta intestata</h2><Field label="Ragione sociale" value={brand.companyName} onChange={v=>setBrand({...brand,companyName:v})}/><Field label="Indirizzo" value={brand.address} onChange={v=>setBrand({...brand,address:v})}/><Field label="Email" value={brand.email} onChange={v=>setBrand({...brand,email:v})}/><Field label="Telefono" value={brand.phone} onChange={v=>setBrand({...brand,phone:v})}/><Field label="P. IVA" value={brand.vatNumber} onChange={v=>setBrand({...brand,vatNumber:v})}/><Field label="Sito" value={brand.website} onChange={v=>setBrand({...brand,website:v})}/><Field label="Footer" value={brand.footerText} onChange={v=>setBrand({...brand,footerText:v})}/><div className="field"><label>Logo</label><input type="file" accept="image/png,image/jpeg" onChange={e=>e.target.files?.[0]&&onLogo(e.target.files[0])}/>{brand.logoDataUrl&&<img className="logo-preview" src={brand.logoDataUrl} alt="logo"/>}</div></>}
function Field({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){return <div className="field"><label>{label}</label><input value={value} onChange={e=>onChange(e.target.value)}/></div>}
function SignatureModal({onClose,onDone}:{onClose:()=>void;onDone:(s:string)=>void}){const canvas=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);useEffect(()=>{const c=canvas.current;if(!c)return;c.width=600;c.height=200;const ctx=c.getContext('2d');if(ctx){ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111827'}},[]);const pos=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return {x:(e.clientX-r.left)*(canvas.current!.width/r.width),y:(e.clientY-r.top)*(canvas.current!.height/r.height)}};return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Disegna la firma</h2><button className="tool" onClick={onClose}>×</button></div><canvas ref={canvas} className="signature-pad" onPointerDown={e=>{drawing.current=true;const p=pos(e);const ctx=canvas.current!.getContext('2d')!;ctx.beginPath();ctx.moveTo(p.x,p.y)}} onPointerMove={e=>{if(!drawing.current)return;const p=pos(e);const ctx=canvas.current!.getContext('2d')!;ctx.lineTo(p.x,p.y);ctx.stroke()}} onPointerUp={()=>drawing.current=false} onPointerLeave={()=>drawing.current=false}/><div className="modal-actions"><label className="btn btn-soft"><PenLine size={16}/> Carica firma<input hidden type="file" accept="image/png,image/jpeg" onChange={async e=>{const f=e.target.files?.[0];if(f)onDone(await fileToDataURL(f))}}/></label><button className="btn btn-soft" onClick={()=>{const c=canvas.current!;c.getContext('2d')!.clearRect(0,0,c.width,c.height)}}>Cancella</button><button className="btn btn-primary" onClick={()=>onDone(canvas.current!.toDataURL('image/png'))}>Usa firma</button></div></div></div>}
function fileToDataURL(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
