'use client';
import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { FileText, Building2, Stamp, Image as ImageIcon, PenTool, Layers3, UploadCloud, LayoutDashboard, Settings } from 'lucide-react';

export default function Home(){
  const router=useRouter(); const input=useRef<HTMLInputElement>(null); const [drag,setDrag]=useState(false); const [status,setStatus]=useState('');
  const handle=async(files:FileList|null)=>{if(!files?.length)return;setStatus(files.length>1?`Creazione PDF da ${files.length} immagini…`:`Elaborazione di ${files[0].name}…`);try{const form=new FormData();Array.from(files).forEach(f=>form.append('files',f));const res=await fetch('/api/documents',{method:'POST',body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||'Caricamento non riuscito');localStorage.setItem('pdfbrand-doc-id',data.id);router.push(`/editor?id=${data.id}`)}catch(e){setStatus((e as Error).message)}};
  return <div className="shell"><header className="topbar"><div className="brand">PDF Brand <span>Studio</span></div><div className="top-actions"><button className="btn btn-soft" disabled title="Autenticazione nella fase successiva">Accedi</button><button className="btn btn-primary" onClick={()=>input.current?.click()}>Nuovo documento</button></div></header><div className="layout"><aside className="sidebar"><div className="navitem active"><LayoutDashboard size={18}/> Dashboard</div><div className="navitem"><FileText size={18}/> Documenti</div><div className="navitem"><Building2 size={18}/> Brand Kit</div><div className="navitem"><Layers3 size={18}/> Template</div><div className="navitem"><Stamp size={18}/> Firme</div><div className="navitem"><Settings size={18}/> Impostazioni</div></aside><main className="content"><section className="hero"><div className="hero-card"><div className="eyebrow">Editor documentale aziendale</div><h1>Trasforma ogni documento in un PDF professionale.</h1><p className="muted">Carica, converti, modifica e applica la tua identità aziendale. Carta intestata, logo, footer e firma in un unico flusso.</p><div className={`upload ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);handle(e.dataTransfer.files)}} onClick={()=>input.current?.click()}><UploadCloud size={34}/><h3>Carica il tuo documento</h3><p className="muted">PDF, DOC, DOCX, JPG o PNG. Puoi selezionare più immagini per unirle in un unico PDF.</p><button className="btn btn-primary">Scegli file</button><input ref={input} hidden multiple type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>handle(e.target.files)}/><div className="status">{status}</div></div></div><div className="card quick"><div className="eyebrow">Azioni rapide</div><h2>Da dove vuoi partire?</h2><div className="quick-grid"><Quick icon={<FileText/>} title="Modifica PDF" text="Apri l'editor completo"/><Quick icon={<Building2/>} title="Applica carta intestata" text="Brand in un click"/><Quick icon={<ImageIcon/>} title="Inserisci logo" text="Posiziona il tuo marchio"/><Quick icon={<PenTool/>} title="Firma documento" text="Carica o disegna la firma"/></div></div></section><div className="section-title"><div><div className="eyebrow">Workspace</div><h2>Il tuo centro documenti</h2></div></div><div className="cards"><Mini title="Documenti persistenti" text="I PDF vengono salvati sul server e possono essere riaperti tramite il loro ID."/><Mini title="Brand Kit" text="Salva logo, dati societari, colori e footer."/><Mini title="Carte intestate" text="Applica automaticamente il brand durante l'esportazione."/><Mini title="Editor visuale" text="Testo, immagini, firma, evidenziatore e gestione pagine."/></div></main></div></div>}
function Quick({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <button className="quick-action" onClick={()=>document.querySelector<HTMLInputElement>('input[type=file]')?.click()}>{icon}<strong>{title}</strong><span>{text}</span></button>}
function Mini({title,text}:{title:string,text:string}){return <div className="card mini"><h3>{title}</h3><p>{text}</p></div>}
